config/routes.rb
Rails.application.routes.draw do

  root 'students#index'

  resources :students do
    resources :classrooms
  end
  resources :courses
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course

  validates :student, :course, :entry_at, presence: true
  validates :student_id, uniqueness: { scope: :course_id }
end

app/models/course.rb
class Course < ActiveRecord::Base

  ACTIVE_STATUS = 1
  INACTIVE_STATUS = 2

  has_many :classrooms
  has_many :students, through: :classrooms

  validates :name, :description, presence: true, length: { maximum: 45}
end

app/models/student.rb
class Student < ActiveRecord::Base

  ACTIVE_STATUS = 1
  INACTIVE_STATUS = 2

  has_many :classrooms
  has_many :courses, through: :classrooms

  validates :name, :register_number, presence: true, length: { maximum: 45}
  validates :register_number, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController

  before_action :set_student
  before_action :set_classroom, only: [:edit, :update]

  def index
    @classrooms = @student.classrooms.includes(:course)
  end

  def new
    @classroom = @student.classrooms.build
    set_courses
  end

  def create
    @classroom = @student.classrooms.build(classroom_params)
    if @classroom.save
      redirect_to student_classrooms_path(@student), notice: t('.success')
    else
      set_courses
      render :new
    end
  end

  def edit
    set_courses
  end

  def update
    if @classroom.update(classroom_params)
      redirect_to student_classrooms_path(@student), notice: t('.success')
    else
      set_courses
      render :edit
    end
  end

  private

  def classroom_params
    params.require(:classroom).permit(:course_id, :entry_at)
  end

  def set_classroom
    @classroom = Classroom.find(params[:id])
  end

  def set_student
    @student = Student.find(params[:student_id])
  end

  def set_courses
    @courses = Course.select(:id, :name)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_action :set_course, only: [:edit, :update]

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path, notice: t('.success')
    else
      render :new
    end
  end

  def edit
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to courses_path, notice: t('.success')
    else
      render :edit
    end
  end

  private

  def course_params
    params.require(:course).permit(:name, :description)
  end

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student, only: [:edit, :update]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path, notice: t('.success')
    else
      render :new
    end
  end

  def edit
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to students_path, notice: t('.success')
    else
      render :edit
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :register_number)
  end

  def set_student
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_errors(resource)
    return if resource.errors.empty?
    content_tag(:div, class: 'alert alert-danger') do
      resource.errors.full_messages.map do |error_message|
        concat(content_tag(:div, error_message))
      end
    end
  end

  def t_attr(model_name, attr_name)
    t("activerecord.attributes.#{model_name}.#{attr_name}")
  end

  def back_button
    link_to t('application.label.back'), root_path, class: 'btn btn-default right'
  end
end

app/views/classrooms/_form.html.erb
<%= show_errors(@classroom) %>

<%= form_for [@student, @classroom] do |f| %>

  <div class="form-group">
    <%= label_tag t_attr(:classroom, :student_id) %>
    <%= text_field_tag :student, @student.name, disabled: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :course %>
      <%= f.collection_select :course_id, @courses, :id, :name, {prompt: t('.select_course_prompt')}, {class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.label :entry_at %>
    <br>
    <%= f.datetime_select :entry_at, {}, class: 'input-medium' %>
  </div>

  <br>

  <%= f.submit nil, class: 'btn btn-default' %>
<% end %>

app/views/classrooms/edit.html.erb
<%= render 'form' %>

app/views/classrooms/index.html.erb
<h1><%= @student.name %> - <%= t('.list_title') %></h1>

<br>

<div class="panel panel-default">
  <table class="table">
      <thead>
        <tr>
          <th><%= t_attr(:classroom, :course) %></th>
          <th><%= t_attr(:classroom, :entry_at) %></th>
          <th></th>
        </tr>
      </thead>
      <% @classrooms.each do |classroom| %>

        <tr>
          <td><%= classroom.course.name %></td>
          <td><%= link_to t('.edit'), edit_student_classroom_path(@student, classroom), class: 'btn btn-default' %></td>
        </tr>
    <% end %>
  </table>

</div>

<%= back_button %>

app/views/classrooms/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/courses/_form.html.erb
<%= show_errors(@course) %>

<%= form_for @course do |f| %>
  
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <%= f.submit nil, class: 'btn btn-default' %>

<% end %>

app/views/courses/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<%= notice %>

<h1><%= t('.list_title') %></h1>

<br>

<%= link_to t('.new'), new_course_path, class: 'btn btn-primary btn-lg' %>

<br>
<br>
<br>

<div class="panel panel-default">
  <table class="table">
      <thead>
        <tr>
          <th><%= t_attr(:course, :name) %></th>
          <th><%= t_attr(:course, :description) %></th>
          <th></th>
        </tr>
      </thead>
      <% @courses.each do |course| %>

        <tr>
          <td><%= course.name %></td>
          <td><%= course.description %></td>
          <td><%= link_to t('.edit'), edit_course_path(course), class: 'btn btn-default' %></td>
        </tr>

    <% end %>
  </table>

</div>

app/views/courses/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Repense', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('.students'), students_path %></li>
        <li><%= link_to t('.courses'), courses_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_message.html.erb
<% if notice %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Repense</title>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/menu' %>

    <div class="container" role="main">
      <div class="jumbotron">
        <%= render 'layouts/message' %>
        <%= yield %>
      </div>
    </div> 
  </body>
</html>

app/views/students/_form.html.erb
<% @student.errors.full_messages.each do |full_message| %>
  <%= full_message %>
<% end %>

<%= form_for @student do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :register_number %>
  <%= f.text_field :register_number %>

  <%= f.submit %>

<% end %>

app/views/students/index.html.erb
<h1><%= t('.list_title') %></h1>

<br>

<%= link_to t('.new'), new_student_path, class: 'btn btn-primary btn-lg' %>

<br>
<br>
<br>

<div class="panel panel-default">
  <table class="table">
      <thead>
        <tr>
          <th><%= t_attr(:student, :name) %></th>
          <th><%= t_attr(:student, :register_number) %></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <% @students.each do |student| %>

        <tr>
          <td><%= student.name %></td>
          <td><%= student.register_number %></td>
          <td><%= link_to t('.edit'), edit_student_path(student), class: 'btn btn-default' %></td>
          <td><%= link_to t('.apply'), new_student_classroom_path(student), class: 'btn btn-default' %></td>
          <td><%= link_to t('.classrooms') + " (#{student.classrooms.count})", student_classrooms_path(student), class: 'btn btn-default' %></td>
        </tr>
    <% end %>
  </table>

</div>

app/views/students/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>